#!/bin/bash


## 
## You must install mingw for compiling go to windows binary
## sudo apt install gcc-mingw-w64
##

## To regenerate the syso file, you need to run the following command:
## go-winres simply --icon jxwatcher.ico --product-version 1.0.0 --file-version 1.0.0 --product-name "JXWatcher"
##
## You can install go-winres with the following command:
## go install github.com/tc-hib/go-winres@latest

## To regenerate the .ico file, you can copy the following function into your .bashrc or bash_profile
## and then run the command `svgtoico jxwatcher scalable/jxwatcher.svg windows/jxwatcher.ico`
## This function uses Inkscape to convert SVG to PNG and ImageMagick to convert PNGs to ICO.
##
## Make sure you have Inkscape and ImageMagick installed:
## sudo apt install inkscape imagemagick    
##
# svgtoico(){
#     # $1: Base name for the icon (e.g., "my_icon")
#     # $2: Path to the source SVG file (e.g., "path/to/my_icon.svg")
#     # $3: Desired path for the output ICO file (e.g., "path/to/output.ico")

#     # Create temporary PNG files for different sizes
#     inkscape -w 16 -h 16 -o "$1-16.png" "$2"
#     inkscape -w 32 -h 32 -o "$1-32.png" "$2"
#     inkscape -w 48 -h 48 -o "$1-48.png" "$2"
#     inkscape -w 256 -h 256 -o "$1-256.png" "$2"

#     # Combine PNGs into an ICO file
#     convert "$1-16.png" "$1-32.png" "$1-48.png" "$1-256.png" "$1.ico"

#     # Clean up temporary PNG files
#     rm "$1-16.png" "$1-32.png" "$1-48.png" "$1-256.png"

#     # Move the generated ICO to the desired location
#     mv "$1.ico" "$3"
# }



echo "Generating Windows binary"

## Copying the rsrc_win.syso file to the root directory
## This file is generated by go-winres and contains the Windows resource information
cp assets/windows/rsrc_windows_amd64.syso .

## Setup the flags
## -pthread will speed up the compile time
## -w -s will create smallest file possible
## -H=windowsgui is needed to fix windows showing terminal eventhough this is a GUI program
GOOS=windows \
GOARCH=amd64  \
CGO_ENABLED=1 \
CGO_CFLAGS="-pthread" \
CGO_LDFLAGS="-pthread" \
CC=/usr/bin/x86_64-w64-mingw32-gcc \
go build -tags production -ldflags "-w -s -H=windowsgui" -o build/jxwatcher.exe .

if [ $? -eq 0 ]; then
    echo "Windows binary created successfully: build/jxwatcher.exe"
else
    echo "Failed to create Windows binary."
fi

# Clean up the rsrc_win.syso file
rm rsrc_windows_amd64.syso