package core

const EPSILON = 1e-9
const NETWORKING_SUCCESS = 0
const NETWORKING_ERROR_CONNECTION = -1
const NETWORKING_URL_ERROR = -2
const NETWORKING_DATA_IN_CACHE = -3
const NETWORKING_UNAUTHORIZED = -4
const NETWORKING_BAD_DATA_RECEIVED = -5
const NETWORKING_BAD_CONFIG = -6
const NETWORKING_BAD_PAYLOAD = -7
const NETWORKING_FAILED_CREATE_FILE = -8

const STATE_LOADED = 0
const STATE_LOADING = -1
const STATE_ERROR = -2
const STATE_FETCHING_NEW = -3

const VALUE_INCREASE = 1
const VALUE_NO_CHANGE = 0
const VALUE_DECREASE = -1

const NO_SNAPSHOT = -1
const HAVE_SNAPSHOT = 0
