package core

/** Generated message constant */
const NotifyApplicationIsStarting = "Application is starting..."
const NotifyConfigurationSavedSuccessfully = "Configuration saved successfully."
const NotifyCryptoMapRegeneratedSuccessfully = "Crypto map regenerated successfully"
const NotifyExchangeFetchCompleted = "Exchange fetch completed."
const NotifyFailedToConvertCryptoDataToMap = "Failed to convert crypto data to map"
const NotifyFailedToCreateCryptosDataFile = "Failed to create cryptos data file"
const NotifyFailedToFetchCryptosData = "Failed to fetch cryptos data"
const NotifyFailedToLoadCryptosData = "Failed to load cryptos data"
const NotifyFailedToSaveConfiguration = "Failed to save configuration."
const NotifyFailedToSavePanelSettings = "Failed to save panel settings."
const NotifyFetchingTheLatestExchangeRates = "Fetching the latest exchange rates..."
const NotifyFetchingTheLatestTickerData = "Fetching the latest ticker data..."
const NotifyInvalidConfigurationUnableToResetCryptos = "Invalid configuration. Unable to reset cryptos map."
const NotifyNewPanelCreated = "New panel created."
const NotifyPanelDisplayRefreshedWithLatestRates = "Panel display refreshed with latest rates"
const NotifyPanelRemovedSuccessfully = "Panel removed successfully."
const NotifyPanelSettingsSaved = "Panel settings saved."
const NotifyPanelsHaveBeenReorderedAndUpdated = "Panels have been reordered and updated."
const NotifyPleaseCheckYourNetworkConnection = "Please check your network connection."
const NotifyPleaseCheckYourSettings = "Please check your settings."
const NotifyRequestingLatestCryptosDataFromExchange = "Requesting latest cryptos data from exchange..."
const NotifySavingConfiguration = "Saving configuration..."
const NotifySavingPanelSettings = "Saving panel settings..."
const NotifySuccessfullyRetrievedCryptosDataFromExch = "Successfully retrieved cryptos data from exchange."
const NotifyTickerDisplayRefreshedWithNewRates = "Ticker display refreshed with new rates"
const NotifyTickerFetchCompleted = "Ticker fetch completed."
const NotifyUnableToAddNewPanelPleaseTryAgain = "Unable to add new panel. Please try again."
const NotifyUnableToLoadPanelsDataFromFile = "Unable to load panels data from file."
const NotifyUnableToUpdatePanelPleaseTryAgain = "Unable to update panel. Please try again."
