# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: JxWatcher

on:
  push:
    tags:
      - 'v*' # Trigger on tagged commits (e.g., v1.2.3)

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build
      run: ./build-linux.sh && ./build-windows.sh
